###### Content for header / footer
title: Sustainamo
author: Content by Ash Bladon
description: 

# email: ""
url: https://sustainamo.com
baseurl: "/sustainamo"


##### Site config stuff

theme: minima
markdown: kramdown
kramdown:
  input: GFM

timezone: Etc/UTC # GitHub uses UTC. This is to force dev environment to match
future: false # GitHub Pages will publish future posts if this isn't set to false

# Minima variables
github_username:   ashterism
instagram_username: asherture
rss: rss

home_post_limit: 5   # Change to show more posts
show_excerpts: false

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gfm-admonitions


  # titles_from_headings:
  # strip_title: true
  # collections: true
