###### Content for header / footer
title: Sustainamo
author: Content by Ash Bladon
description: A free, comprehensive guide to creating and implementing a meaningful sustainability strategy # This will also show up in places like twitter, linkedin, etc, if you share your sites url as a post.

baseurl: ""  # Required for Cloudflare Pages

# email: ""
# url: https://sustainamo.com

##### Site config stuff

theme: minima
markdown: kramdown
kramdown:
  input: GFM

timezone: Etc/UTC 
future: false # GitHub Pages will publish future posts if this isn't set to false

# Minima variables
github_username: sustainamo
# instagram_username: 
rss: rss

collections_dir: style-guide
collections:
  basics:
    output: false
    permalink: /style-guide/basics/:name/
  components:
    output: false
    permalink: /style-guide/components/:name/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  sass_dir: assets/css
